export const MADUREZ_TOOLTIPS = {
  "Planificación productiva": "Capacidad para coordinar los cultivos de la base social con antelación, basándose en la demanda esperada para evitar excedentes o faltas de producto.",
  "Gestión comercial": "Capacidad para buscar proactivamente nuevos clientes, fijar precios rentables y mantener una relación fluida con los canales de venta.",
  "Costes de producción": "Capacidad de calcular y hacer un seguimiento real de cuánto cuesta producir y final distribución de cada producto para garantizar la viabilidad.",
  "Logística": "Eficiencia en la recogida, almacenamiento (en frío o en seco), preparación de pedidos y distribución física al cliente final o punto intermedio.",
  "Calidad": "Estandarización de calibres, maduración, presentación del producto, y protocolos de revisión y gestión de mermas e incidencias.",
  "Digitalización": "Uso sistemático de herramientas digitales (ERP, POD, etc.) para la gestión integral, trazabilidad, facturación y catálogo de productos.",
  "Gobernanza interna": "Claridad en los procesos de toma de decisiones, roles asignados y nivel de participación democrática y cohesión de la base social.",
  "Marketing": "Generación de una identidad clara, materiales comerciales y presencia (digital o física) para poner en valor el proyecto y sus productos.",
  "Administración": "Solidez y orden en la contabilidad, fiscalidad, facturación, cobros/pagos y trámites burocráticos.",
  "Restauración colectiva": "Experiencia y capacidad para servir a colegios, hospitales u otros comedores públicos/privados de forma constante."
};

export const blocks = [
  {
    id: 0,
    title: "Validación ficha",
    icon: "📋",
    intro: "Se ha preparado desde la red una ficha con los datos básicos de cada agrupación. Se invita a revisarla e indicar si hay algo que actualizar.",
    questions: [
      { id: "0.1", q: "¿Los datos de la ficha enviada son correctos?", type: "radio", options: ["Sí, todo correcto", "No, hay datos que actualizar"] },
      { id: "0.2", q: "Si hay datos que actualizar, indicar cuáles.", type: "textarea", conditional: true },
      { id: "0.3", q: "Persona de contacto principal para intercooperación económica (nombre, cargo, email, teléfono).", type: "textarea" },
      { id: "0.4", q: "¿Hay una segunda persona de contacto para estos temas?", type: "textarea", optional: true },
    ],
  },
  {
    id: 1,
    title: "Gobernanza interna",
    icon: "🤝",
    intro: "Resulta importante entender cómo se organiza y toma decisiones cada agrupación. Cada CAD tiene su forma de funcionar, y eso condiciona cómo se puede cooperar entre todos.",
    questions: [
      { id: "1.1", q: "¿Cómo se toman las decisiones comerciales en el CAD?", type: "radio", options: ["El equipo técnico/gerencia tiene autonomía para decisiones del día a día", "Las decisiones relevantes pasan por una comisión o grupo de trabajo", "Las decisiones importantes requieren aprobación de la junta/asamblea", "No hay un proceso definido, se va decidiendo sobre la marcha"], hasOther: true },
      { id: "1.2", q: "¿Quién coordina actualmente la oferta y la relación con clientes?", type: "radio", options: ["Equipo técnico / personal contratado con dedicación", "Una comisión comercial de personas socias", "La junta directiva o coordinación general, entre otras tareas", "Liderazgos informales de socios/as", "No hay nadie con esa función clara"], hasOther: true },
      { id: "1.3", q: "¿Se ha tratado internamente el tema de comprar o vender producto a otros CAD de la red?", type: "radio", options: ["Sí, y hay respaldo claro para avanzar", "Sí, pero hay dudas o resistencias que se están trabajando", "No, todavía no se ha planteado formalmente", "No aplica, la decisión la toma el equipo técnico directamente"] },
      { id: "1.4", q: "Si hay dudas o resistencias internas, ¿cuáles son?", type: "textarea", optional: true },
      { id: "1.5", q: "¿Cómo se describiría la relación entre el equipo técnico y la base social productora?", type: "radio", options: ["Fuerte: las personas productoras confían y participan activamente", "Funcional: la delegación funciona, aunque la participación es limitada", "Frágil: hay tensiones o desconexión", "No aplica: son las propias personas productoras quienes gestionan el CAD"], hasOther: true },
      { id: "1.6", q: "¿Existe algún servicio o rol externalizado clave para el funcionamiento del CAD?", type: "textarea", optional: true },
    ],
  },
  {
    id: 2,
    title: "Modelo de negocio",
    icon: "📊",
    intro: "Como red es importante tener una imagen clara de dónde está cada agrupación. Como se planteó en Granada: \"tener un espacio donde expresar necesidades, poder compartir un momento económico complicado\".",
    questions: [
      { id: "2.1", q: "Volumen aproximado de facturación anual.", type: "radio", options: ["Menos de 50.000 €", "50.000 – 150.000 €", "150.000 – 300.000 €", "300.000 – 600.000 €", "600.000 – 1.000.000 €", "1.000.000 – 1.500.000 €", "Más de 1.500.000 €", "Se prefiere no compartir de momento"], hasComment: true },
      { id: "2.2", q: "¿Cómo ha evolucionado la facturación en los últimos 3 años?", type: "radio", options: ["Crecimiento sostenido (>10% anual)", "Crecimiento moderado (<10% anual)", "Estable", "Irregular (altibajos significativos)", "Descenso", "Sin histórico suficiente", "Se prefiere no compartir"], hasOther: true },
      { id: "2.3", q: "¿El CAD genera resultado positivo?", type: "radio", options: ["Sí, resultado positivo consolidado", "Equilibrio (sin pérdidas pero sin margen significativo)", "Resultado negativo pero dentro de lo previsto", "Resultado negativo y situación complicada", "No se dispone de cierre definitivo", "Se prefiere no compartir de momento"], hasOther: true, hasComment: true },
      { id: "2.4", q: "Distribución aproximada de facturación por canal de venta.", type: "info", description: "Canales habituales: Comedores escolares, Restauración/HORECA, Tiendas eco, Grupos de consumo, Gran distribución, Venta a otros CAD, Venta directa, Exportación. Indica en los comentarios los canales principales y su peso aproximado." },
      { id: "2.5", q: "¿Cómo de concentrada está la cartera de clientes?", type: "radio", options: ["Diversificada (los 3 principales < 25%)", "Moderadamente concentrada (25-50%)", "Concentrada (> 50%)"], hasComment: true },
      { id: "2.6", q: "¿Existe experiencia con contratos de suministro estables o plurianuales?", type: "radio", options: ["Sí, es la forma habitual con determinados clientes", "Sí, con algunos clientes", "No, pero interesaría", "No, y no se ve viable ahora", "Se ha tenido, pero ya no"], hasOther: true },
      { id: "2.7", q: "Estacionalidad de la facturación.", type: "radio", options: ["Alta estacionalidad (grandes picos y valles)", "Moderada con picos claros en determinados meses", "Regular pero con dependencia de algún canal concreto", "Baja (bastante regular todo el año)", "Variable según tipo de producto"], hasOther: true, hasComment: true },
      { id: "2.8", q: "¿Cuál es la política de márgenes comerciales?", type: "radio", options: ["Margen fijo sobre precio de compra, igual para todos los productos", "Margen diferenciado por producto y/o canal", "No hay política establecida, se va viendo"], hasOther: true, hasComment: true },
      { id: "2.9", q: "¿De qué herramientas de seguimiento económico se dispone?", type: "checkbox", options: ["Software de gestión (POD, ERP u otro)", "Control de márgenes por producto", "Control de costes logísticos", "Cálculo de costes de producción", "Contabilidad analítica por línea de negocio", "Presupuesto anual o plan de viabilidad", "Cuadro de mando o indicadores", "Excel / hojas de cálculo propias", "Asesoría externa contable/fiscal", "No se dispone de herramientas específicas"], hasOther: true, hasComment: true },
    ],
  },
  {
    id: 3,
    title: "Capacidad operativa",
    icon: "⚙️",
    intro: "Esta sección se centra en la capacidad real de cada agrupación para participar en intercambios: recursos, infraestructura y organización disponibles hoy.",
    questions: [
      { id: "3.1", q: "¿El CAD realiza planificación productiva o coordinación de oferta con sus socias?", type: "radio", options: ["Sí, de forma regular", "Sí, pero solo para determinados productos o campañas", "Coordinación informal, sin planificación estructurada", "No existe coordinación de oferta"], hasOther: true, hasComment: true },
      { id: "3.2", q: "¿Cómo se recoge la disponibilidad de producto de las personas socias?", type: "radio", options: ["Formato estructurado con periodicidad fija (catálogo, ERP, POD)", "Mensajería (WhatsApp/Telegram) y recopilación manual", "Llamadas o correos puntuales cuando hay demanda", "Cada socia gestiona por su cuenta", "En diseño, se quiere implementar"], hasOther: true },
      { id: "3.3", q: "¿Se podría hoy consolidar y servir un pedido conjunto a otro CAD o cliente externo?", type: "radio", options: ["Sí, con facilidad", "Sí, pero con esfuerzo o solo para ciertos productos", "Difícil hoy (falta estructura, tiempo o herramientas)", "No es una función que se asuma como CAD"], hasOther: true, hasComment: true },
      { id: "3.4", q: "Modelo de abastecimiento predominante.", type: "radio", options: ["Solo producción de socias", "Producción de socias + compras externas con proveedores estables", "Producción de socias + compras externas según necesidad", "Mayoritariamente compras externas"], hasOther: true },
      { id: "3.5", q: "Alcance habitual de distribución.", type: "checkbox", options: ["Local / comarcal", "Provincial", "Autonómico", "Interautonómico", "Estatal"], hasOther: true, hasComment: true },
      { id: "3.5a", q: "¿El alcance de distribución varía según el tipo de producto?", type: "radio", options: ["No, es similar para todos los productos", "Sí, el fresco se distribuye en radio más reducido", "Sí, hay productos estatales y otros solo locales"], hasOther: true, hasComment: true },
      { id: "3.6", q: "¿Se dispone de flota logística propia?", type: "radio", options: ["Sí, íntegramente propia", "Mixta (propia + subcontratada)", "Totalmente subcontratada", "No se realiza distribución directa"], hasOther: true, hasComment: true },
      { id: "3.7", q: "Capacidad de almacenamiento en frío.", type: "radio", options: ["No se dispone de frío", "Pequeña capacidad (< 100 m²)", "Media (100-300 m²)", "Alta (> 300 m²)"], hasOther: true, hasComment: true },
      { id: "3.8", q: "¿Qué software de gestión se utiliza actualmente?", type: "checkbox", options: ["POD", "Otro ERP (especificar)", "Excel / hojas de cálculo", "No se utiliza software específico"], hasOther: true, hasComment: true },
      { id: "3.8a", q: "¿El CAD funciona o podría funcionar como centro de acopio para la red?", type: "radio", options: ["Sí, ya funciona como centro de acopio para las socias", "Sí, y podría ser punto de acopio intermedio para otros CAD", "No actualmente, pero se dispone de infraestructura", "No se dispone de infraestructura ni capacidad"], hasOther: true, hasComment: true },
      { id: "3.8b", q: "¿Cuál es el tiempo de respuesta habitual para servir un pedido?", type: "radio", options: ["24 horas", "48 horas", "72 horas", "1 semana o más", "Variable según producto y época"], hasOther: true, hasComment: true },
      { id: "3.9", q: "Principales dificultades para coordinar oferta entre las personas socias.", type: "checkbox", options: ["Falta de tiempo / sobrecarga de trabajo", "Falta de herramienta común", "Producciones muy diversas", "Estacionalidad y discontinuidad", "Diferencias de precios entre socias", "Logística", "Falta de liderazgo o roles claros", "Falta de infraestructuras", "Limitaciones digitales de las socias", "Limitaciones de conectividad", "Perfil de edad avanzada de la base social", "Dificultad para encontrar personal técnico"], hasOther: true, hasComment: true },
    ],
  },
  {
    id: 4,
    title: "Oferta y necesidades",
    icon: "🌱",
    intro: "Las grandes líneas de oferta disponible y necesidades de abastecimiento. El detalle fino se trabajará aparte con los datos de los sistemas de gestión.",
    questions: [
      { id: "4.1", q: "¿Qué grandes familias de producto puede ofrecer el CAD?", type: "checkbox", options: ["Huerta / hortalizas", "Fruta", "Cítricos", "Frutos secos", "Olivar / aceite", "Viña / vino", "Cereales / legumbres", "Carne", "Lácteos", "Huevos", "Apicultura", "Transformados", "Panadería / harinas", "Bebidas"], hasOther: true },
      { id: "4.2", q: "¿Existen excedentes estructurales o picos de producción recurrentes?", type: "radio", options: ["Sí, de forma estructural en varias categorías", "Sí, pero solo estacionalmente o en productos concretos", "No, se vende prácticamente todo"] },
      { id: "4.3", q: "Si existen excedentes o picos, ¿en qué categorías y en qué época del año?", type: "textarea", optional: true },
      { id: "4.4", q: "¿El CAD necesita abastecerse regularmente de productos externos a su base social?", type: "radio", options: ["Sí, de forma estructural", "Sí, de forma estacional", "Puntualmente, para productos concretos", "No, casi todo proviene de las personas socias"], hasOther: true },
      { id: "4.5", q: "¿Qué categorías de producto se necesita adquirir externamente?", type: "checkbox", options: ["Huerta / hortalizas", "Fruta", "Cítricos", "Frutos secos", "Olivar / aceite", "Cereales / legumbres", "Carne", "Lácteos", "Transformados", "Panadería / harinas", "Bebidas"], hasOther: true },
      { id: "4.6", q: "¿Existe disposición a ofrecer producto a otros CAD de la red?", type: "radio", options: ["Sí, es algo que ya se hace o se quiere hacer", "Sí, si se dan condiciones mínimas", "No hay capacidad de oferta, pero sí de facilitar apertura de mercado en el territorio", "Interesa pero se necesita madurar internamente", "No se ve viable ahora mismo"], hasOther: true, hasComment: true },
      { id: "4.7", q: "¿Existe disposición a sustituir compras externas por compras a otros CAD?", type: "radio", options: ["Sí, si las condiciones son competitivas", "Sí, aunque se priorizarían proveedores locales actuales", "Habría que valorarlo según producto y condiciones", "No se ve viable"] },
      { id: "4.8", q: "¿Se está intercambiando ya producto con algún otro CAD de la red?", type: "textarea", optional: true },
    ],
  },
  {
    id: 5,
    title: "Calidad",
    icon: "✅",
    intro: "Una de las oportunidades de la red es acceder conjuntamente a canales de venta que individualmente resultan difíciles. Para plantear estas oportunidades, es importante conocer la capacidad de calidad y servicio a nivel de red.",
    questions: [
      { id: "5.1", q: "¿Se dispone de fichas técnicas de los productos?", type: "radio", options: ["Sí, para todos o la mayoría", "Sí, pero solo para algunos productos o clientes", "No, pero se está trabajando en ello", "No"], hasOther: true, hasComment: true },
      { id: "5.2", q: "¿Existe algún tipo de política o protocolo de calidad?", type: "radio", options: ["Sí, con protocolo escrito y persona responsable", "Hay criterios compartidos pero no formalizados", "Se gestiona caso a caso", "No"], hasOther: true, hasComment: true },
      { id: "5.3", q: "¿Hay alguien revisando el producto antes de salir al cliente?", type: "radio", options: ["Sí, siempre, con criterios definidos", "Sí, de forma visual/informal", "Solo para determinados clientes o productos", "No, va directamente de la socia al cliente"], hasOther: true, hasComment: true },
      { id: "5.4", q: "¿Se dispone de certificaciones adicionales a la ecológica?", type: "checkbox", options: ["GlobalGAP", "Demeter", "Comercio justo", "Residuo cero o similar", "ISO / AENOR", "BRC / IFS", "Ninguna adicional"], hasOther: true },
      { id: "5.5", q: "En materia de trazabilidad y registros, ¿cuál es la situación?", type: "radio", options: ["Trazabilidad completa para todos los productos", "Trazabilidad completa para la mayoría", "Se cumple con lo que exigen las auditorías", "Trazabilidad parcial, hay margen de mejora", "No hay sistema estructurado"], hasOther: true, hasComment: true },
      { id: "5.5a", q: "¿Cómo se gestiona la relación con auditorías y controles oficiales?", type: "checkbox", options: ["Auditorías CAE sin incidencias", "Inspecciones de sanidad sin incidencias", "Ha habido incidencias o no conformidades recientes", "Gestión de auditorías con persona dedicada", "Recae en quien lleva otras tareas", "Se externaliza la preparación"], hasOther: true, hasComment: true },
      { id: "5.6", q: "¿Se han tenido incidencias de devolución de producto en el último año?", type: "radio", options: ["No, prácticamente ninguna", "Puntualmente (< 5 al año)", "Con cierta frecuencia (> 5 al año)", "Es un problema recurrente"], hasComment: true },
      { id: "5.7", q: "¿Podría adaptarse el etiquetado a las necesidades de un cliente conjunto de la red?", type: "radio", options: ["Sí, sin problema", "Sí, pero requeriría inversión o cambios", "Habría que valorarlo", "No se ve viable"] },
    ],
  },
  {
    id: 6,
    title: "Identidad y comunicación",
    icon: "🌐",
    intro: "La red está dando sus primeros pasos. Una de las cuestiones que se ha ido planteando es cómo presentarse hacia fuera y cómo comunicarse entre las agrupaciones.",
    questions: [
      { id: "6.1", q: "¿Resultaría interesante que la red disponga de una imagen colectiva?", type: "radio", options: ["Sí, sería útil para visibilidad y acciones conjuntas", "Sí, pero manteniendo la identidad propia de cada agrupación", "No se ve prioritario ahora"], hasOther: true, hasComment: true },
      { id: "6.2", q: "¿Qué herramientas compartidas serían útiles para la red?", type: "checkbox", options: ["Web pública con presentación de agrupaciones y oferta", "Espacio privado / intranet con información interna", "Catálogo o herramienta comercial conjunta", "Fichas de presentación de cada CAD", "Materiales de comunicación compartidos", "No se ve necesario por ahora"], hasOther: true, hasComment: true },
      { id: "6.3", q: "Para la comunicación interna entre agrupaciones, ¿qué canales funcionarían mejor?", type: "checkbox", options: ["Correo electrónico como canal principal", "Grupo de difusión WhatsApp/Telegram (solo lectura)", "Grupo de conversación WhatsApp/Telegram", "Comunidad con canales temáticos", "Repositorio en Drive bien organizado", "Con el mail es suficiente, no añadir más herramientas"], hasOther: true, hasComment: true },
      { id: "6.4", q: "¿Existe interés en un proceso de acogida o apadrinamiento para nuevas agrupaciones?", type: "radio", options: ["Sí, y habría disposición a apadrinar", "Sí, buena idea aunque no se pueda asumir ahora", "No se ve prioritario"], hasOther: true, hasComment: true },
    ],
  },
  {
    id: 7,
    title: "Expectativas y prioridades",
    icon: "🎯",
    intro: "Para terminar, resulta importante conocer qué se espera de este proceso y dónde se pondrían las prioridades. Como se viene planteando desde Valencia: \"hay que cuidar la red para que la red nos cuide\".",
    questions: [
      { id: "7.1", q: "¿Qué se espera que aporte la intercooperación económica?", type: "checkbox", options: ["Complementar la oferta con productos de otros territorios", "Dar salida a excedentes", "Acceder conjuntamente a nuevos canales", "Mejorar eficiencia operativa", "Espacio de apoyo en momentos difíciles", "Fuerza de negociación conjunta", "Horquilla de precios compartida", "Estandarizar procesos y herramientas"], hasOther: true, hasComment: true },
      { id: "7.2", q: "¿Qué se espera que aporte la intercooperación técnica?", type: "checkbox", options: ["Formaciones prácticas sobre temas compartidos", "Intercambio de experiencias entre agrupaciones", "Repositorio de materiales y buenas prácticas", "Asesoramiento adaptado al nivel de madurez", "Conocer cómo trabajan otros CAD (visitas, sesiones)", "Grupos de trabajo con continuidad", "Canal ágil para consultas informales"], hasOther: true, hasComment: true },
      { id: "7.3", q: "¿Qué se espera en materia de gobernanza y participación?", type: "checkbox", options: ["Participar en el Grupo Motor", "Contribuir al Plan Estratégico", "Tener voz sin estar necesariamente en el Grupo Motor", "Información clara y periódica de la actividad de la red", "Participar en formulación de proyectos conjuntos", "Que la red facilite acceso a financiación"], hasOther: true, hasComment: true },
      { id: "7.4", q: "Prioridades para este año por línea de trabajo.", type: "info", description: "Valora las siguientes áreas según la prioridad que le darías este año: Intercambios entre CAD, Acciones comerciales conjuntas, Formación técnica, Gobernanza, Proyectos conjuntos. (Esta matriz se desarrollará en una siguiente fase.)" },
      { id: "7.5", q: "Capacidad de dedicación real por línea de trabajo.", type: "info", description: "Valora tu capacidad real de dedicación en cada línea: Alta, Media, Baja o Nula este año. (Esta matriz se desarrollará en una siguiente fase.)" },
      { id: "7.6", q: "¿Hay interés en participar en el Grupo Motor de la red?", type: "radio", options: ["Sí, hay interés y disponibilidad", "Hay interés pero no tiempo suficiente ahora", "No, pero sí en estar informados"], hasOther: true, hasComment: true },
      { id: "7.7", q: "¿Hay algo más que se quiera compartir?", type: "textarea", optional: true },
    ],
  },
];
